build:
  maxIssues: 0

complexity:
  active: true
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10

style:
  active: true
  MaxLineLength:
    maxLineLength: 120
    excludeCommentStatements: true
  WildcardImport:
    active: false
